apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: scp-keyvault-01
  labels: 
    azure.azureauthority.in: aks-apps
    app: asset-manager
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3246eb8e-055c-410a-a50c-3aa64c2b45e1"
    keyvaultName: kvproject31177
    objects:  |
      array:
        - |
          objectName: asset-manager-connectionstrings
          objectType: secret
          objectAlias: connectionstrings.json
    tenantId: cf36141c-ddd7-45a7-b073-111f66d0b30c